enum Action {
	StartBreak,
	AbortBreak,
	StopBreak,
	GetUpdatedBlock,
	DropItem,
	StartSleeping,
	StopSleeping,
	Respawn,
	Jump,
	StartSprint,
	StopSprint,
	StartSneak,
	StopSneak,
	CreativePlayerDestroyBlock,
	DimensionChangeAck,
	StartGlide,
	StopGlide,
	BuildDenied,
	CrackBlock,
	ChangeSkin,
	SetEnchantmentSeed,
	StartSwimming,
	StopSwimming,
	StartSpinAttack,
	StopSpinAttack,
	InteractBlock,
	PredictDestroyBlock,
	ContinueDestroyBlock,
	StartItemUseOn,
	StopItemUseOn,
}

export { Action };
