enum Action {
	StartBreak,
	AbortBreak,
	StopBreak,
	GetUpdatedBlock,
	DropItem,
	StartSleeping,
	StopSleeping,
	Respawn,
	Jump,
	StartSprint,
	StopSprint,
	StartSneak,
	StopSneak,
	CreativePlayerDestroyBlock,
	DimensionChangeAck,
	StartGlide,
	StopGlide,
	BuildDenied,
	CrackBreak,
	ChangeSkin,
	SetEnchatnmentSeed, // No longer used
	Swimming,
	StopSwimming,
	StartSpinAttack,
	StopSpinAttack,
	InteractBlock,
	PredictBreak,
	ContinueBreak,
	StartItemUseOn,
	StopItemUseOn,
	HandledTeleport,
	MissedSwing,
	StartCrawling,
	StopCrawling,
}

export { Action };
